name: Main
on:
  push:
    branches: [ main ]
    
env:
  SPECTRAL_DSN: ${{ secrets.https://spu-00da256dfd274d71a55d5834a4b3d516@get.spectralops.io
 }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and run Spectral CI
      uses: spectralops/spectral-github-action@v2
      with:
        spectral-dsn: ${{ env.https://spu-00da256dfd274d71a55d5834a4b3d516@get.spectralops.io
 }}
        spectral-args: scan --ok --include-tags base,audit,iac
